//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondaryStructureTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://wss.cbs.dtu.dk:80/cgi-bin/soap/ws/quasi.fcgi")]
        public string SecondaryStructureTool_dk_dtu_cbs_www_WSTMHMM_2_0_ws1 {
            get {
                return ((string)(this["SecondaryStructureTool_dk_dtu_cbs_www_WSTMHMM_2_0_ws1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ebi.ac.uk/Tools/services/soap/emboss_pepstats")]
        public string SecondaryStructureTool_uk_ac_ebi_www_JDispatcherService {
            get {
                return ((string)(this["SecondaryStructureTool_uk_ac_ebi_www_JDispatcherService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ebi.ac.uk/ws/services/WSDbfetchDoclit")]
        public string SecondaryStructureTool_uk_ac_ebi_www1_WSDBFetchDoclitServerService {
            get {
                return ((string)(this["SecondaryStructureTool_uk_ac_ebi_www1_WSDBFetchDoclitServerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ebi.ac.uk/ws/services/WSDbfetch")]
        public string SecondaryStructureTool_uk_ac_ebi_www_fetch_WSDBFetchServerService {
            get {
                return ((string)(this["SecondaryStructureTool_uk_ac_ebi_www_fetch_WSDBFetchServerService"]));
            }
        }
    }
}
