//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace SecondaryStructureTool.dk.dtu.cbs.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSTMHMM_2_0_ws1", Namespace="http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1")]
    public partial class WSTMHMM_2_0_ws1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback runServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback pollQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSTMHMM_2_0_ws1() {
            this.Url = global::SecondaryStructureTool.Properties.Settings.Default.SecondaryStructureTool_dk_dtu_cbs_www_WSTMHMM_2_0_ws1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event runServiceCompletedEventHandler runServiceCompleted;
        
        /// <remarks/>
        public event pollQueueCompletedEventHandler pollQueueCompleted;
        
        /// <remarks/>
        public event fetchResultCompletedEventHandler fetchResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1#runService", RequestNamespace="http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1", ResponseNamespace="http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("queueentry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
        public runServiceResponseQueueentry runService([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Namespace="http://www.cbs.dtu.dk/ws/ws-tmhmm")] runServiceParameters parameters) {
            object[] results = this.Invoke("runService", new object[] {
                        parameters});
            return ((runServiceResponseQueueentry)(results[0]));
        }
        
        /// <remarks/>
        public void runServiceAsync(runServiceParameters parameters) {
            this.runServiceAsync(parameters, null);
        }
        
        /// <remarks/>
        public void runServiceAsync(runServiceParameters parameters, object userState) {
            if ((this.runServiceOperationCompleted == null)) {
                this.runServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunServiceOperationCompleted);
            }
            this.InvokeAsync("runService", new object[] {
                        parameters}, this.runServiceOperationCompleted, userState);
        }
        
        private void OnrunServiceOperationCompleted(object arg) {
            if ((this.runServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runServiceCompleted(this, new runServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1#pollQueue", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("pollQueueResponse", Namespace="http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1")]
        public pollQueueResponse pollQueue([System.Xml.Serialization.XmlElementAttribute("pollQueue", Namespace="http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1")] pollQueue pollQueue1) {
            object[] results = this.Invoke("pollQueue", new object[] {
                        pollQueue1});
            return ((pollQueueResponse)(results[0]));
        }
        
        /// <remarks/>
        public void pollQueueAsync(pollQueue pollQueue1) {
            this.pollQueueAsync(pollQueue1, null);
        }
        
        /// <remarks/>
        public void pollQueueAsync(pollQueue pollQueue1, object userState) {
            if ((this.pollQueueOperationCompleted == null)) {
                this.pollQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpollQueueOperationCompleted);
            }
            this.InvokeAsync("pollQueue", new object[] {
                        pollQueue1}, this.pollQueueOperationCompleted, userState);
        }
        
        private void OnpollQueueOperationCompleted(object arg) {
            if ((this.pollQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pollQueueCompleted(this, new pollQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1#fetchResult", RequestNamespace="http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1", ResponseNamespace="http://www.cbs.dtu.dk/ws/WSTMHMM_2_0_ws1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("anndata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Namespace="http://www.cbs.dtu.dk/ws/ws-tmhmm")]
        public anndata fetchResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Namespace="http://www.cbs.dtu.dk/ws/ws-common")] fetchResultJob job) {
            object[] results = this.Invoke("fetchResult", new object[] {
                        job});
            return ((anndata)(results[0]));
        }
        
        /// <remarks/>
        public void fetchResultAsync(fetchResultJob job) {
            this.fetchResultAsync(job, null);
        }
        
        /// <remarks/>
        public void fetchResultAsync(fetchResultJob job, object userState) {
            if ((this.fetchResultOperationCompleted == null)) {
                this.fetchResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchResultOperationCompleted);
            }
            this.InvokeAsync("fetchResult", new object[] {
                        job}, this.fetchResultOperationCompleted, userState);
        }
        
        private void OnfetchResultOperationCompleted(object arg) {
            if ((this.fetchResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchResultCompleted(this, new fetchResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-tmhmm")]
    public partial class runServiceParameters {
        
        private sequence[] sequencedataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public sequence[] sequencedata {
            get {
                return this.sequencedataField;
            }
            set {
                this.sequencedataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class sequence {
        
        private string idField;
        
        private string commentField;
        
        private string seqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seq {
            get {
                return this.seqField;
            }
            set {
                this.seqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class anndata {
        
        private anndataAnnsource annsourceField;
        
        private anndataAnn[] annField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anndataAnnsource annsource {
            get {
                return this.annsourceField;
            }
            set {
                this.annsourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ann", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anndataAnn[] ann {
            get {
                return this.annField;
            }
            set {
                this.annField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class anndataAnnsource {
        
        private string methodField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class anndataAnn {
        
        private sequence sequenceField;
        
        private anndataAnnAnnrecord[] annrecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sequence sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("annrecord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public anndataAnnAnnrecord[] annrecords {
            get {
                return this.annrecordsField;
            }
            set {
                this.annrecordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class anndataAnnAnnrecord {
        
        private string featureField;
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private anndataAnnAnnrecordScore[] scoreField;
        
        private anndataAnnAnnrecordStrand strandField;
        
        private bool strandFieldSpecified;
        
        private anndataAnnAnnrecordFrame frameField;
        
        private bool frameFieldSpecified;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("global", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("pos", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        [System.Xml.Serialization.XmlElementAttribute("range", typeof(anndataAnnAnnrecordRange), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("score", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anndataAnnAnnrecordScore[] score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anndataAnnAnnrecordStrand strand {
            get {
                return this.strandField;
            }
            set {
                this.strandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strandSpecified {
            get {
                return this.strandFieldSpecified;
            }
            set {
                this.strandFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public anndataAnnAnnrecordFrame frame {
            get {
                return this.frameField;
            }
            set {
                this.frameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool frameSpecified {
            get {
                return this.frameFieldSpecified;
            }
            set {
                this.frameFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class anndataAnnAnnrecordRange {
        
        private string beginField;
        
        private string endField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cbs.dtu.dk/ws/ws-common", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":global")]
        global,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":pos")]
        pos,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":range")]
        range,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class anndataAnnAnnrecordScore {
        
        private string keyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public enum anndataAnnAnnrecordStrand {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("+")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("-")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public enum anndataAnnAnnrecordFrame {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class pollQueueResponse {
        
        private pollQueueResponseQueueentry queueentryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pollQueueResponseQueueentry queueentry {
            get {
                return this.queueentryField;
            }
            set {
                this.queueentryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class pollQueueResponseQueueentry {
        
        private string jobidField;
        
        private string datetimeField;
        
        private jobstatus statusField;
        
        private string expiresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobid {
            get {
                return this.jobidField;
            }
            set {
                this.jobidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public jobstatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public enum jobstatus {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UNKNOWN JOBID")]
        UNKNOWNJOBID,
        
        /// <remarks/>
        QUEUED,
        
        /// <remarks/>
        REJECTED,
        
        /// <remarks/>
        FINISHED,
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        WAITING,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("QUEUE DOWN")]
        QUEUEDOWN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DATABASE DOWN")]
        DATABASEDOWN,
        
        /// <remarks/>
        FAILED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class pollQueue {
        
        private pollQueueJob jobField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pollQueueJob job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class pollQueueJob {
        
        private string jobidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobid {
            get {
                return this.jobidField;
            }
            set {
                this.jobidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class runServiceResponseQueueentry {
        
        private string jobidField;
        
        private string datetimeField;
        
        private jobstatus statusField;
        
        private string expiresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobid {
            get {
                return this.jobidField;
            }
            set {
                this.jobidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public jobstatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cbs.dtu.dk/ws/ws-common")]
    public partial class fetchResultJob {
        
        private string jobidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string jobid {
            get {
                return this.jobidField;
            }
            set {
                this.jobidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void runServiceCompletedEventHandler(object sender, runServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public runServiceResponseQueueentry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((runServiceResponseQueueentry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void pollQueueCompletedEventHandler(object sender, pollQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pollQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pollQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public pollQueueResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((pollQueueResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void fetchResultCompletedEventHandler(object sender, fetchResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public anndata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((anndata)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591